// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWFwxmYNaWXWrTDSfLqaPq265Opc5-CzM',
    appId: '1:448798247434:web:7fbc98bab2f15325742df3',
    messagingSenderId: '448798247434',
    projectId: 'seventh-abacus-413008',
    authDomain: 'seventh-abacus-413008.firebaseapp.com',
    storageBucket: 'seventh-abacus-413008.appspot.com',
    measurementId: 'G-RS40ZMZG1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyjU38gBv0qyWo4b0it7VHRWVed2sItYo',
    appId: '1:448798247434:android:5396f34f4076ea36742df3',
    messagingSenderId: '448798247434',
    projectId: 'seventh-abacus-413008',
    storageBucket: 'seventh-abacus-413008.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE2_MxZmFP5pXY5Cfc0F-_ywq3IHDTb7Q',
    appId: '1:448798247434:ios:2fdbd2d79f940cfb742df3',
    messagingSenderId: '448798247434',
    projectId: 'seventh-abacus-413008',
    storageBucket: 'seventh-abacus-413008.appspot.com',
    iosBundleId: 'com.example.myProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE2_MxZmFP5pXY5Cfc0F-_ywq3IHDTb7Q',
    appId: '1:448798247434:ios:2fdbd2d79f940cfb742df3',
    messagingSenderId: '448798247434',
    projectId: 'seventh-abacus-413008',
    storageBucket: 'seventh-abacus-413008.appspot.com',
    iosBundleId: 'com.example.myProject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWFwxmYNaWXWrTDSfLqaPq265Opc5-CzM',
    appId: '1:448798247434:web:356fb82675bdd81c742df3',
    messagingSenderId: '448798247434',
    projectId: 'seventh-abacus-413008',
    authDomain: 'seventh-abacus-413008.firebaseapp.com',
    storageBucket: 'seventh-abacus-413008.appspot.com',
    measurementId: 'G-SVZ1LNGXN6',
  );
}
